SELECT TOP (1000) [isbn]
      ,[book_title]
      ,[category]
      ,[rental_price]
      ,[status]
      ,[author]
      ,[publisher]
  FROM [Library Management System].[dbo].[books]

SELECT TOP (1000) [branch_id]
      ,[manager_id]
      ,[branch_address]
      ,[contact_no]
  FROM [Library Management System].[dbo].[branch]

SELECT TOP (1000) [emp_id]
      ,[emp_name]
      ,[position]
      ,[salary]
      ,[branch_id]
  FROM [Library Management System].[dbo].[employees]

SELECT TOP (1000) [issued_id]
      ,[issued_member_id]
      ,[issued_book_name]
      ,[issued_date]
      ,[issued_book_isbn]
      ,[issued_emp_id]
  FROM [Library Management System].[dbo].[issued_status]

SELECT TOP (1000) [member_id]
      ,[member_name]
      ,[member_address]
      ,[reg_date]
  FROM [Library Management System].[dbo].[members]

SELECT TOP (1000) [return_id]
      ,[issued_id]
      ,[return_book_name]
      ,[return_date]
      ,[return_book_isbn]
  FROM [Library Management System].[dbo].[return_status]